<<<<<<< HEAD
<ul id="master-menu" class="m-menu__nav  m-menu__nav--submenu-arrow "><li id="_0201000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs"  m-menu-submenu-toggle="tab" aria-haspopup="true"><a  href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Dashboard</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a><div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span><ul class="m-menu__subnav"><li class="m-menu__item "  m-menu-link-redirect="1" aria-haspopup="true"><a  href="http://inspection.tap-agri.com/dashboard" class="m-menu__link "><i class="m-menu__link-icon fa fa-dashboard"></i><span class="m-menu__link-text">Dashboard</span></a></li></ul></div></li><li id="_0203000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs"  m-menu-submenu-toggle="tab" aria-haspopup="true"><a  href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Report</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a><div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span><ul class="m-menu__subnav"><li class="m-menu__item "  m-menu-link-redirect="1" aria-haspopup="true"><a  href="http://inspection.tap-agri.com/report-oracle/download" class="m-menu__link "><i class="m-menu__link-icon fa fa-cloud-download"></i><span class="m-menu__link-text">Download</span></a></li></ul></div></li></ul>
=======
<<<<<<< HEAD
<ul id="master-menu" class="m-menu__nav  m-menu__nav--submenu-arrow "><li id="_0201000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs"  m-menu-submenu-toggle="tab" aria-haspopup="true"><a  href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Dashboard</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a><div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span><ul class="m-menu__subnav"><li class="m-menu__item "  m-menu-link-redirect="1" aria-haspopup="true"><a  href="http://inspectiondev.tap-agri.com/dashboard" class="m-menu__link "><i class="m-menu__link-icon fa fa-dashboard"></i><span class="m-menu__link-text">Dashboard</span></a></li></ul></div></li><li id="_0203000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs"  m-menu-submenu-toggle="tab" aria-haspopup="true"><a  href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Report</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a><div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span><ul class="m-menu__subnav"><li class="m-menu__item "  m-menu-link-redirect="1" aria-haspopup="true"><a  href="http://inspectiondev.tap-agri.com/report-oracle/download" class="m-menu__link "><i class="m-menu__link-icon fa fa-cloud-download"></i><span class="m-menu__link-text">Download</span></a></li></ul></div></li></ul>
=======
<ul id="master-menu" class="m-menu__nav  m-menu__nav--submenu-arrow ">
    <li id="_0201000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true"><a href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Dashboard</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a>
        <div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span>
            <ul class="m-menu__subnav">
                <li class="m-menu__item " m-menu-link-redirect="1" aria-haspopup="true"><a href={{ URL::to('/dashboard') }} class="m-menu__link "><i class="m-menu__link-icon fa fa-dashboard"></i><span class="m-menu__link-text">Dashboard</span></a></li>
            </ul>
        </div>
    </li>
    <li id="_0203000000_" class="m-menu__item   m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true"><a href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__link-text">Report</span><i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i></a>
        <div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs"><span class="m-menu__arrow m-menu__arrow--adjust"></span>
            <ul class="m-menu__subnav">
                <li class="m-menu__item " m-menu-link-redirect="1" aria-haspopup="true"><a href={{ URL::to('/report-oracle/download') }} class="m-menu__link "><i class="m-menu__link-icon fa fa-cloud-download"></i><span class="m-menu__link-text">Download</span></a></li>
            </ul>
        </div>
    </li>
</ul>
>>>>>>> e090cdccb72d964e30c691a74e2948e058054cc1
>>>>>>> e726e819a221eba0d3ecfa2e9864d863574f832f
